FROM python:3.14-slim AS builder

WORKDIR /app
COPY requirements.txt ./
RUN pip install --target=/install --no-compile -r requirements.txt

FROM python:3.14-slim
WORKDIR /app
COPY --from=builder /install /usr/local/lib/python3.14/site-packages

EXPOSE 8080
CMD ["python", "src/main.py"]
